// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;
import 'package:google_sign_in/google_sign_in.dart';
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart';

final GoogleSignInPlatform googleSignInPlatform = GoogleSignInPlatform.instance;
final GoogleSignIn googleSignIn = GoogleSignIn.instance;

class CodeFarmsFirebaseOptions {
  final String projectId;
  final String region;
  final String googleSignInClientId;
  final String serverClientId;
  final FirebaseOptions web;
  final FirebaseOptions android;
  final FirebaseOptions ios;

  CodeFarmsFirebaseOptions({
    required this.projectId,
    required this.region,
    required this.googleSignInClientId,
    required this.serverClientId,
    required this.web,
    required this.android,
    required this.ios,
  });

  FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
